name: 7.4-main

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/build_7_4-main.yml'
      - '7.4/**'
      - 'overlay/**'
      - 'VERSION'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read PHP version - revision
        uses: bencgreen/read-file-action@v1
        with:
          path: ./7.4/PHP_REVISION
        id: php_revision
      -
        name: Read PHP version - build
        uses: bencgreen/read-file-action@v1
        with:
          path: ./7.4/PHP_BUILD
        id: php_build
      -
        name: Read image version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./7.4/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          #platforms: linux/amd64,linux/arm/v7
          #platforms: linux/amd64,linux/arm64
          tags: |
            bcgdesign/wordpress:latest
            bcgdesign/wordpress:${{ steps.version.outputs.content }}
            bcgdesign/wordpress:php-7
            bcgdesign/wordpress:php-7.4
            bcgdesign/wordpress:php-${{ steps.php_revision.outputs.content }}
            bcgdesign/wordpress:php-${{ steps.php_build.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
