name: main-php7_3

on:
  release:
    types: [published]

jobs:
  publish-php7_3:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read PHP version - revision
        uses: bencgreen/read-file-action@v1
        with:
          path: ./php7.3/PHP_REVISION
        id: php_revision
      -
        name: Read PHP version - build
        uses: bencgreen/read-file-action@v1
        with:
          path: ./php7.3/PHP_BUILD
        id: php_build
      -
        name: Read WP version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./WP_MINOR
        id: wp_version
      -
        name: Read image version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./php7.3/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bcgdesign/wordpress:php7.3
            bcgdesign/wordpress:php7.3-${{ steps.version.outputs.content }}
            bcgdesign/wordpress:php7.3-wp${{ steps.wp_version.outputs.content }}
            bcgdesign/wordpress:php7.3-wp${{ steps.wp_version.outputs.content }}-${{ steps.version.outputs.content }}
            bcgdesign/wordpress:php${{ steps.php_revision.outputs.content }}
            bcgdesign/wordpress:php${{ steps.php_build.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
